#####################################
# modsecurity.conf minimal pour Docker
#####################################

# 1️⃣ Active ModSecurity
SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess off

# # --- Limites du corps de requête (en octets) ---
SecRequestBodyLimit 1048576
# # ------------------------------------------------

# 2️⃣ Audit log (toutes les requêtes bloquées seront loggées)
SecAuditEngine On
SecAuditLogFormat JSON
SecAuditLog /dev/stdout
# SecAuditLog /tmp/modsec_audit.log
SecAuditLogParts ABIJDEFHZ
SecAuditLogType Serial

# 3️⃣ Debug log pour voir toutes les règles évaluées
SecDebugLog /tmp/modsec_debug.log
SecDebugLogLevel 9

# 4️⃣ Règle custom : bloque toute URI contenant "test"
# SecRule REQUEST_URI "@contains test" \
#     "id:1001,phase:1,deny,status:403,msg:'Blocked request containing test',log,ctl:auditEngine=On"

# # Interdire méthodes non utilisées / deja bloquee par NGINX
# SecRule REQUEST_METHOD "!^(GET|POST|OPTIONS)$" "id:1002,phase:1,deny,status:405,msg:'Method not allowed'"
#SecAction "id:1003,phase:1,pass,nolog,initcol:ip=%{REMOTE_ADDR},expirevar:ip.brute=600"
# SecRule REQUEST_URI "@contains /login" "id:1004,phase:2,pass,nolog,setvar:ip.brute=+1,msg:'increment brute counter'"
# SecRule IP:brute "@gt 5" "id:1005,phase:2,deny,status:403,msg:'Too many login attempts'"


# -------- CRS --------

Include /opt/owasp-crs/crs-setup.conf

# reglages avant CRS
Include /etc/modsecurity/override-before.conf

# regles CRS
Include /opt/owasp-crs/rules/*.conf

# reglages apres CRS 
Include /etc/modsecurity/override-after.conf